### ISSUE TITLE
Exception using .net 6

### ISSUE THREAD

**Issue by beachwalker** [Arch/AutoHistory#73]
When trying to run it with .net 6 and ef core 6.0.1 this throws an exception during startup.

```
System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
   at Microsoft.EntityFrameworkCore.DbContextExtensions.AutoHistory[TAutoHistory](EntityEntry entry, Func`1 createHistoryFactory)
   at Microsoft.EntityFrameworkCore.DbContextExtensions.EnsureAutoHistory[TAutoHistory](DbContext context, Func`1 createHistoryFactory)
   at Microsoft.EntityFrameworkCore.DbContextExtensions.EnsureAutoHistory(DbContext context)
```

**Comment by lostatredrock** [comment]
I cloned the current repo, included this in my project and it solved this problem for me so guessing the project just needs a new build pushed to nuget  for Net 6.  Is this something in the works?

**Comment by NormanGiHu** [comment]
We get this exception since ef core 6 and .net 6:
Method not found: 'System.String Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.

**Comment by xyting** [comment]
maybe this weekend

**Comment by GeorgeLeithead** [comment]
I'm still getting the error:
System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
Using:

- Microsoft.EntityFrameworkCore" Version="6.0.4"
- Microsoft.EntityFrameworkCore.AutoHistory" Version="5.0.8"

**Comment by LinQiaoPorco** [comment]
> We get this exception since ef core 6 and .net 6: Method not found: 'System.String Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.

I got this error, too, when I migrate from .Net 5 to .Net 6.
```
OS: Ubuntu 18.04;
DotNet SDK: 6.0.300;
```

**Comment by NewGHUser4321** [comment]
> I'm still getting the error: System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'. Using:
> 
> * Microsoft.EntityFrameworkCore" Version="6.0.4"
> * Microsoft.EntityFrameworkCore.AutoHistory" Version="5.0.8"

Same with me. Any help would be appreciated.

Thanks,

**Comment by hhwwrr110** [comment]
if you download from nuget it will throw this exception , you can clone this repository,and relaase it.

**Comment by LinQiaoPorco** [comment]
> > We get this exception since ef core 6 and .net 6: Method not found: 'System.String Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.
> 
> I got this error, too, when I migrate from .Net 5 to .Net 6.
> 
> ```
> OS: Ubuntu 18.04;
> DotNet SDK: 6.0.300;
> ```

Add `Microsoft.EntityFrameworkCore.Relational` solves the problem for me, have no idea if it worked for you.

**Comment by HyderAli1990** [comment]
Is there any fix or workaround for this issue?
@xyting 
Help would be appreciated

**Comment by LinQiaoPorco** [comment]
> Is there any fix or workaround for this issue? @xyting Help would be appreciated

Try to Add `Microsoft.EntityFrameworkCore.Relational` package.

**Comment by xyting** [comment]
very very sorry, please update to version [v6](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory/6.0.0)
